# Generated by Django 3.2.7 on 2021-09-26 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='number',
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
