# Generated by Django 3.2.7 on 2021-10-03 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
